name: Daily Script Run

on:
  schedule:
    # Run every day at 5:00 AM UTC
    - cron: "0 5 * * *"
  workflow_dispatch: # (optional) lets you trigger manually

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python (if it’s a Python script)
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run script
        run: python ./database/pubmed_update.py
